// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.cormye.common.proto;

public interface ClientOnlineOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ClientOnline)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string tx2Id = 1;</code>
   */
  java.lang.String getTx2Id();
  /**
   * <code>string tx2Id = 1;</code>
   */
  com.google.protobuf.ByteString
      getTx2IdBytes();

  /**
   * <code>string tx2Ip = 2;</code>
   */
  java.lang.String getTx2Ip();
  /**
   * <code>string tx2Ip = 2;</code>
   */
  com.google.protobuf.ByteString
      getTx2IpBytes();
}
