// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.cormye.common.proto;

/**
 * <pre>
 *对应HeadType的CLIENT_ONLINE
 * </pre>
 *
 * Protobuf type {@code ClientOnline}
 */
public  final class ClientOnline extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ClientOnline)
    ClientOnlineOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ClientOnline.newBuilder() to construct.
  private ClientOnline(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ClientOnline() {
    tx2Id_ = "";
    tx2Ip_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ClientOnline(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            tx2Id_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            tx2Ip_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.cormye.common.proto.TranData.internal_static_ClientOnline_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.cormye.common.proto.TranData.internal_static_ClientOnline_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.cormye.common.proto.ClientOnline.class, com.cormye.common.proto.ClientOnline.Builder.class);
  }

  public static final int TX2ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object tx2Id_;
  /**
   * <code>string tx2Id = 1;</code>
   */
  public java.lang.String getTx2Id() {
    java.lang.Object ref = tx2Id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tx2Id_ = s;
      return s;
    }
  }
  /**
   * <code>string tx2Id = 1;</code>
   */
  public com.google.protobuf.ByteString
      getTx2IdBytes() {
    java.lang.Object ref = tx2Id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tx2Id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TX2IP_FIELD_NUMBER = 2;
  private volatile java.lang.Object tx2Ip_;
  /**
   * <code>string tx2Ip = 2;</code>
   */
  public java.lang.String getTx2Ip() {
    java.lang.Object ref = tx2Ip_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tx2Ip_ = s;
      return s;
    }
  }
  /**
   * <code>string tx2Ip = 2;</code>
   */
  public com.google.protobuf.ByteString
      getTx2IpBytes() {
    java.lang.Object ref = tx2Ip_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tx2Ip_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getTx2IdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, tx2Id_);
    }
    if (!getTx2IpBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, tx2Ip_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getTx2IdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, tx2Id_);
    }
    if (!getTx2IpBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, tx2Ip_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.cormye.common.proto.ClientOnline)) {
      return super.equals(obj);
    }
    com.cormye.common.proto.ClientOnline other = (com.cormye.common.proto.ClientOnline) obj;

    boolean result = true;
    result = result && getTx2Id()
        .equals(other.getTx2Id());
    result = result && getTx2Ip()
        .equals(other.getTx2Ip());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TX2ID_FIELD_NUMBER;
    hash = (53 * hash) + getTx2Id().hashCode();
    hash = (37 * hash) + TX2IP_FIELD_NUMBER;
    hash = (53 * hash) + getTx2Ip().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.cormye.common.proto.ClientOnline parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cormye.common.proto.ClientOnline parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cormye.common.proto.ClientOnline parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cormye.common.proto.ClientOnline parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cormye.common.proto.ClientOnline parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cormye.common.proto.ClientOnline parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cormye.common.proto.ClientOnline parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cormye.common.proto.ClientOnline parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cormye.common.proto.ClientOnline parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.cormye.common.proto.ClientOnline parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cormye.common.proto.ClientOnline parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cormye.common.proto.ClientOnline parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.cormye.common.proto.ClientOnline prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *对应HeadType的CLIENT_ONLINE
   * </pre>
   *
   * Protobuf type {@code ClientOnline}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ClientOnline)
      com.cormye.common.proto.ClientOnlineOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cormye.common.proto.TranData.internal_static_ClientOnline_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cormye.common.proto.TranData.internal_static_ClientOnline_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cormye.common.proto.ClientOnline.class, com.cormye.common.proto.ClientOnline.Builder.class);
    }

    // Construct using com.cormye.common.proto.ClientOnline.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      tx2Id_ = "";

      tx2Ip_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.cormye.common.proto.TranData.internal_static_ClientOnline_descriptor;
    }

    @java.lang.Override
    public com.cormye.common.proto.ClientOnline getDefaultInstanceForType() {
      return com.cormye.common.proto.ClientOnline.getDefaultInstance();
    }

    @java.lang.Override
    public com.cormye.common.proto.ClientOnline build() {
      com.cormye.common.proto.ClientOnline result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.cormye.common.proto.ClientOnline buildPartial() {
      com.cormye.common.proto.ClientOnline result = new com.cormye.common.proto.ClientOnline(this);
      result.tx2Id_ = tx2Id_;
      result.tx2Ip_ = tx2Ip_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.cormye.common.proto.ClientOnline) {
        return mergeFrom((com.cormye.common.proto.ClientOnline)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.cormye.common.proto.ClientOnline other) {
      if (other == com.cormye.common.proto.ClientOnline.getDefaultInstance()) return this;
      if (!other.getTx2Id().isEmpty()) {
        tx2Id_ = other.tx2Id_;
        onChanged();
      }
      if (!other.getTx2Ip().isEmpty()) {
        tx2Ip_ = other.tx2Ip_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.cormye.common.proto.ClientOnline parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.cormye.common.proto.ClientOnline) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object tx2Id_ = "";
    /**
     * <code>string tx2Id = 1;</code>
     */
    public java.lang.String getTx2Id() {
      java.lang.Object ref = tx2Id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tx2Id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string tx2Id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTx2IdBytes() {
      java.lang.Object ref = tx2Id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tx2Id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string tx2Id = 1;</code>
     */
    public Builder setTx2Id(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      tx2Id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string tx2Id = 1;</code>
     */
    public Builder clearTx2Id() {
      
      tx2Id_ = getDefaultInstance().getTx2Id();
      onChanged();
      return this;
    }
    /**
     * <code>string tx2Id = 1;</code>
     */
    public Builder setTx2IdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      tx2Id_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object tx2Ip_ = "";
    /**
     * <code>string tx2Ip = 2;</code>
     */
    public java.lang.String getTx2Ip() {
      java.lang.Object ref = tx2Ip_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tx2Ip_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string tx2Ip = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTx2IpBytes() {
      java.lang.Object ref = tx2Ip_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tx2Ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string tx2Ip = 2;</code>
     */
    public Builder setTx2Ip(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      tx2Ip_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string tx2Ip = 2;</code>
     */
    public Builder clearTx2Ip() {
      
      tx2Ip_ = getDefaultInstance().getTx2Ip();
      onChanged();
      return this;
    }
    /**
     * <code>string tx2Ip = 2;</code>
     */
    public Builder setTx2IpBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      tx2Ip_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ClientOnline)
  }

  // @@protoc_insertion_point(class_scope:ClientOnline)
  private static final com.cormye.common.proto.ClientOnline DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.cormye.common.proto.ClientOnline();
  }

  public static com.cormye.common.proto.ClientOnline getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ClientOnline>
      PARSER = new com.google.protobuf.AbstractParser<ClientOnline>() {
    @java.lang.Override
    public ClientOnline parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ClientOnline(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ClientOnline> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ClientOnline> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.cormye.common.proto.ClientOnline getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

