// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.cormye.common.proto;

public final class TranData {
  private TranData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code PackType}
   */
  public enum PackType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *客户端上线 发送自己的ip和设备编号
     * </pre>
     *
     * <code>CLIENT_ONLINE = 0;</code>
     */
    CLIENT_ONLINE(0),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     *客户端上线 发送自己的ip和设备编号
     * </pre>
     *
     * <code>CLIENT_ONLINE = 0;</code>
     */
    public static final int CLIENT_ONLINE_VALUE = 0;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PackType valueOf(int value) {
      return forNumber(value);
    }

    public static PackType forNumber(int value) {
      switch (value) {
        case 0: return CLIENT_ONLINE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PackType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        PackType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PackType>() {
            public PackType findValueByNumber(int number) {
              return PackType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.cormye.common.proto.TranData.getDescriptor().getEnumTypes().get(0);
    }

    private static final PackType[] VALUES = values();

    public static PackType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private PackType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:PackType)
  }

  public interface TransProtocolOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TransProtocol)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *数据包类型
     * </pre>
     *
     * <code>.PackType packType = 1;</code>
     */
    int getPackTypeValue();
    /**
     * <pre>
     *数据包类型
     * </pre>
     *
     * <code>.PackType packType = 1;</code>
     */
    com.cormye.common.proto.TranData.PackType getPackType();

    /**
     * <code>.ClientOnline clientOnline = 2;</code>
     */
    boolean hasClientOnline();
    /**
     * <code>.ClientOnline clientOnline = 2;</code>
     */
    com.cormye.common.proto.TranData.ClientOnline getClientOnline();
    /**
     * <code>.ClientOnline clientOnline = 2;</code>
     */
    com.cormye.common.proto.TranData.ClientOnlineOrBuilder getClientOnlineOrBuilder();

    public com.cormye.common.proto.TranData.TransProtocol.PackBodyCase getPackBodyCase();
  }
  /**
   * <pre>
   *定义传输对象  也是整个数据包的根对象
   * </pre>
   *
   * Protobuf type {@code TransProtocol}
   */
  public  static final class TransProtocol extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TransProtocol)
      TransProtocolOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TransProtocol.newBuilder() to construct.
    private TransProtocol(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TransProtocol() {
      packType_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TransProtocol(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              packType_ = rawValue;
              break;
            }
            case 18: {
              com.cormye.common.proto.TranData.ClientOnline.Builder subBuilder = null;
              if (packBodyCase_ == 2) {
                subBuilder = ((com.cormye.common.proto.TranData.ClientOnline) packBody_).toBuilder();
              }
              packBody_ =
                  input.readMessage(com.cormye.common.proto.TranData.ClientOnline.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.cormye.common.proto.TranData.ClientOnline) packBody_);
                packBody_ = subBuilder.buildPartial();
              }
              packBodyCase_ = 2;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cormye.common.proto.TranData.internal_static_TransProtocol_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cormye.common.proto.TranData.internal_static_TransProtocol_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cormye.common.proto.TranData.TransProtocol.class, com.cormye.common.proto.TranData.TransProtocol.Builder.class);
    }

    private int packBodyCase_ = 0;
    private java.lang.Object packBody_;
    public enum PackBodyCase
        implements com.google.protobuf.Internal.EnumLite {
      CLIENTONLINE(2),
      PACKBODY_NOT_SET(0);
      private final int value;
      private PackBodyCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static PackBodyCase valueOf(int value) {
        return forNumber(value);
      }

      public static PackBodyCase forNumber(int value) {
        switch (value) {
          case 2: return CLIENTONLINE;
          case 0: return PACKBODY_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public PackBodyCase
    getPackBodyCase() {
      return PackBodyCase.forNumber(
          packBodyCase_);
    }

    public static final int PACKTYPE_FIELD_NUMBER = 1;
    private int packType_;
    /**
     * <pre>
     *数据包类型
     * </pre>
     *
     * <code>.PackType packType = 1;</code>
     */
    public int getPackTypeValue() {
      return packType_;
    }
    /**
     * <pre>
     *数据包类型
     * </pre>
     *
     * <code>.PackType packType = 1;</code>
     */
    public com.cormye.common.proto.TranData.PackType getPackType() {
      @SuppressWarnings("deprecation")
      com.cormye.common.proto.TranData.PackType result = com.cormye.common.proto.TranData.PackType.valueOf(packType_);
      return result == null ? com.cormye.common.proto.TranData.PackType.UNRECOGNIZED : result;
    }

    public static final int CLIENTONLINE_FIELD_NUMBER = 2;
    /**
     * <code>.ClientOnline clientOnline = 2;</code>
     */
    public boolean hasClientOnline() {
      return packBodyCase_ == 2;
    }
    /**
     * <code>.ClientOnline clientOnline = 2;</code>
     */
    public com.cormye.common.proto.TranData.ClientOnline getClientOnline() {
      if (packBodyCase_ == 2) {
         return (com.cormye.common.proto.TranData.ClientOnline) packBody_;
      }
      return com.cormye.common.proto.TranData.ClientOnline.getDefaultInstance();
    }
    /**
     * <code>.ClientOnline clientOnline = 2;</code>
     */
    public com.cormye.common.proto.TranData.ClientOnlineOrBuilder getClientOnlineOrBuilder() {
      if (packBodyCase_ == 2) {
         return (com.cormye.common.proto.TranData.ClientOnline) packBody_;
      }
      return com.cormye.common.proto.TranData.ClientOnline.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (packType_ != com.cormye.common.proto.TranData.PackType.CLIENT_ONLINE.getNumber()) {
        output.writeEnum(1, packType_);
      }
      if (packBodyCase_ == 2) {
        output.writeMessage(2, (com.cormye.common.proto.TranData.ClientOnline) packBody_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (packType_ != com.cormye.common.proto.TranData.PackType.CLIENT_ONLINE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, packType_);
      }
      if (packBodyCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (com.cormye.common.proto.TranData.ClientOnline) packBody_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.cormye.common.proto.TranData.TransProtocol)) {
        return super.equals(obj);
      }
      com.cormye.common.proto.TranData.TransProtocol other = (com.cormye.common.proto.TranData.TransProtocol) obj;

      boolean result = true;
      result = result && packType_ == other.packType_;
      result = result && getPackBodyCase().equals(
          other.getPackBodyCase());
      if (!result) return false;
      switch (packBodyCase_) {
        case 2:
          result = result && getClientOnline()
              .equals(other.getClientOnline());
          break;
        case 0:
        default:
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PACKTYPE_FIELD_NUMBER;
      hash = (53 * hash) + packType_;
      switch (packBodyCase_) {
        case 2:
          hash = (37 * hash) + CLIENTONLINE_FIELD_NUMBER;
          hash = (53 * hash) + getClientOnline().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.cormye.common.proto.TranData.TransProtocol parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cormye.common.proto.TranData.TransProtocol parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cormye.common.proto.TranData.TransProtocol parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cormye.common.proto.TranData.TransProtocol parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cormye.common.proto.TranData.TransProtocol parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cormye.common.proto.TranData.TransProtocol parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cormye.common.proto.TranData.TransProtocol parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.cormye.common.proto.TranData.TransProtocol parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.cormye.common.proto.TranData.TransProtocol parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.cormye.common.proto.TranData.TransProtocol parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.cormye.common.proto.TranData.TransProtocol parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.cormye.common.proto.TranData.TransProtocol parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.cormye.common.proto.TranData.TransProtocol prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *定义传输对象  也是整个数据包的根对象
     * </pre>
     *
     * Protobuf type {@code TransProtocol}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TransProtocol)
        com.cormye.common.proto.TranData.TransProtocolOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cormye.common.proto.TranData.internal_static_TransProtocol_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cormye.common.proto.TranData.internal_static_TransProtocol_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cormye.common.proto.TranData.TransProtocol.class, com.cormye.common.proto.TranData.TransProtocol.Builder.class);
      }

      // Construct using com.cormye.common.proto.TranData.TransProtocol.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        packType_ = 0;

        packBodyCase_ = 0;
        packBody_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cormye.common.proto.TranData.internal_static_TransProtocol_descriptor;
      }

      @java.lang.Override
      public com.cormye.common.proto.TranData.TransProtocol getDefaultInstanceForType() {
        return com.cormye.common.proto.TranData.TransProtocol.getDefaultInstance();
      }

      @java.lang.Override
      public com.cormye.common.proto.TranData.TransProtocol build() {
        com.cormye.common.proto.TranData.TransProtocol result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.cormye.common.proto.TranData.TransProtocol buildPartial() {
        com.cormye.common.proto.TranData.TransProtocol result = new com.cormye.common.proto.TranData.TransProtocol(this);
        result.packType_ = packType_;
        if (packBodyCase_ == 2) {
          if (clientOnlineBuilder_ == null) {
            result.packBody_ = packBody_;
          } else {
            result.packBody_ = clientOnlineBuilder_.build();
          }
        }
        result.packBodyCase_ = packBodyCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cormye.common.proto.TranData.TransProtocol) {
          return mergeFrom((com.cormye.common.proto.TranData.TransProtocol)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.cormye.common.proto.TranData.TransProtocol other) {
        if (other == com.cormye.common.proto.TranData.TransProtocol.getDefaultInstance()) return this;
        if (other.packType_ != 0) {
          setPackTypeValue(other.getPackTypeValue());
        }
        switch (other.getPackBodyCase()) {
          case CLIENTONLINE: {
            mergeClientOnline(other.getClientOnline());
            break;
          }
          case PACKBODY_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.cormye.common.proto.TranData.TransProtocol parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.cormye.common.proto.TranData.TransProtocol) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int packBodyCase_ = 0;
      private java.lang.Object packBody_;
      public PackBodyCase
          getPackBodyCase() {
        return PackBodyCase.forNumber(
            packBodyCase_);
      }

      public Builder clearPackBody() {
        packBodyCase_ = 0;
        packBody_ = null;
        onChanged();
        return this;
      }


      private int packType_ = 0;
      /**
       * <pre>
       *数据包类型
       * </pre>
       *
       * <code>.PackType packType = 1;</code>
       */
      public int getPackTypeValue() {
        return packType_;
      }
      /**
       * <pre>
       *数据包类型
       * </pre>
       *
       * <code>.PackType packType = 1;</code>
       */
      public Builder setPackTypeValue(int value) {
        packType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *数据包类型
       * </pre>
       *
       * <code>.PackType packType = 1;</code>
       */
      public com.cormye.common.proto.TranData.PackType getPackType() {
        @SuppressWarnings("deprecation")
        com.cormye.common.proto.TranData.PackType result = com.cormye.common.proto.TranData.PackType.valueOf(packType_);
        return result == null ? com.cormye.common.proto.TranData.PackType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *数据包类型
       * </pre>
       *
       * <code>.PackType packType = 1;</code>
       */
      public Builder setPackType(com.cormye.common.proto.TranData.PackType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        packType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *数据包类型
       * </pre>
       *
       * <code>.PackType packType = 1;</code>
       */
      public Builder clearPackType() {
        
        packType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.cormye.common.proto.TranData.ClientOnline, com.cormye.common.proto.TranData.ClientOnline.Builder, com.cormye.common.proto.TranData.ClientOnlineOrBuilder> clientOnlineBuilder_;
      /**
       * <code>.ClientOnline clientOnline = 2;</code>
       */
      public boolean hasClientOnline() {
        return packBodyCase_ == 2;
      }
      /**
       * <code>.ClientOnline clientOnline = 2;</code>
       */
      public com.cormye.common.proto.TranData.ClientOnline getClientOnline() {
        if (clientOnlineBuilder_ == null) {
          if (packBodyCase_ == 2) {
            return (com.cormye.common.proto.TranData.ClientOnline) packBody_;
          }
          return com.cormye.common.proto.TranData.ClientOnline.getDefaultInstance();
        } else {
          if (packBodyCase_ == 2) {
            return clientOnlineBuilder_.getMessage();
          }
          return com.cormye.common.proto.TranData.ClientOnline.getDefaultInstance();
        }
      }
      /**
       * <code>.ClientOnline clientOnline = 2;</code>
       */
      public Builder setClientOnline(com.cormye.common.proto.TranData.ClientOnline value) {
        if (clientOnlineBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          packBody_ = value;
          onChanged();
        } else {
          clientOnlineBuilder_.setMessage(value);
        }
        packBodyCase_ = 2;
        return this;
      }
      /**
       * <code>.ClientOnline clientOnline = 2;</code>
       */
      public Builder setClientOnline(
          com.cormye.common.proto.TranData.ClientOnline.Builder builderForValue) {
        if (clientOnlineBuilder_ == null) {
          packBody_ = builderForValue.build();
          onChanged();
        } else {
          clientOnlineBuilder_.setMessage(builderForValue.build());
        }
        packBodyCase_ = 2;
        return this;
      }
      /**
       * <code>.ClientOnline clientOnline = 2;</code>
       */
      public Builder mergeClientOnline(com.cormye.common.proto.TranData.ClientOnline value) {
        if (clientOnlineBuilder_ == null) {
          if (packBodyCase_ == 2 &&
              packBody_ != com.cormye.common.proto.TranData.ClientOnline.getDefaultInstance()) {
            packBody_ = com.cormye.common.proto.TranData.ClientOnline.newBuilder((com.cormye.common.proto.TranData.ClientOnline) packBody_)
                .mergeFrom(value).buildPartial();
          } else {
            packBody_ = value;
          }
          onChanged();
        } else {
          if (packBodyCase_ == 2) {
            clientOnlineBuilder_.mergeFrom(value);
          }
          clientOnlineBuilder_.setMessage(value);
        }
        packBodyCase_ = 2;
        return this;
      }
      /**
       * <code>.ClientOnline clientOnline = 2;</code>
       */
      public Builder clearClientOnline() {
        if (clientOnlineBuilder_ == null) {
          if (packBodyCase_ == 2) {
            packBodyCase_ = 0;
            packBody_ = null;
            onChanged();
          }
        } else {
          if (packBodyCase_ == 2) {
            packBodyCase_ = 0;
            packBody_ = null;
          }
          clientOnlineBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.ClientOnline clientOnline = 2;</code>
       */
      public com.cormye.common.proto.TranData.ClientOnline.Builder getClientOnlineBuilder() {
        return getClientOnlineFieldBuilder().getBuilder();
      }
      /**
       * <code>.ClientOnline clientOnline = 2;</code>
       */
      public com.cormye.common.proto.TranData.ClientOnlineOrBuilder getClientOnlineOrBuilder() {
        if ((packBodyCase_ == 2) && (clientOnlineBuilder_ != null)) {
          return clientOnlineBuilder_.getMessageOrBuilder();
        } else {
          if (packBodyCase_ == 2) {
            return (com.cormye.common.proto.TranData.ClientOnline) packBody_;
          }
          return com.cormye.common.proto.TranData.ClientOnline.getDefaultInstance();
        }
      }
      /**
       * <code>.ClientOnline clientOnline = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.cormye.common.proto.TranData.ClientOnline, com.cormye.common.proto.TranData.ClientOnline.Builder, com.cormye.common.proto.TranData.ClientOnlineOrBuilder> 
          getClientOnlineFieldBuilder() {
        if (clientOnlineBuilder_ == null) {
          if (!(packBodyCase_ == 2)) {
            packBody_ = com.cormye.common.proto.TranData.ClientOnline.getDefaultInstance();
          }
          clientOnlineBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.cormye.common.proto.TranData.ClientOnline, com.cormye.common.proto.TranData.ClientOnline.Builder, com.cormye.common.proto.TranData.ClientOnlineOrBuilder>(
                  (com.cormye.common.proto.TranData.ClientOnline) packBody_,
                  getParentForChildren(),
                  isClean());
          packBody_ = null;
        }
        packBodyCase_ = 2;
        onChanged();;
        return clientOnlineBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TransProtocol)
    }

    // @@protoc_insertion_point(class_scope:TransProtocol)
    private static final com.cormye.common.proto.TranData.TransProtocol DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.cormye.common.proto.TranData.TransProtocol();
    }

    public static com.cormye.common.proto.TranData.TransProtocol getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TransProtocol>
        PARSER = new com.google.protobuf.AbstractParser<TransProtocol>() {
      @java.lang.Override
      public TransProtocol parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TransProtocol(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TransProtocol> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TransProtocol> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.cormye.common.proto.TranData.TransProtocol getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ClientOnlineOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ClientOnline)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string tx2Id = 1;</code>
     */
    java.lang.String getTx2Id();
    /**
     * <code>string tx2Id = 1;</code>
     */
    com.google.protobuf.ByteString
        getTx2IdBytes();

    /**
     * <code>string tx2Ip = 2;</code>
     */
    java.lang.String getTx2Ip();
    /**
     * <code>string tx2Ip = 2;</code>
     */
    com.google.protobuf.ByteString
        getTx2IpBytes();
  }
  /**
   * <pre>
   *对应HeadType的CLIENT_ONLINE
   * </pre>
   *
   * Protobuf type {@code ClientOnline}
   */
  public  static final class ClientOnline extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ClientOnline)
      ClientOnlineOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ClientOnline.newBuilder() to construct.
    private ClientOnline(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ClientOnline() {
      tx2Id_ = "";
      tx2Ip_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ClientOnline(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              tx2Id_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              tx2Ip_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cormye.common.proto.TranData.internal_static_ClientOnline_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cormye.common.proto.TranData.internal_static_ClientOnline_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cormye.common.proto.TranData.ClientOnline.class, com.cormye.common.proto.TranData.ClientOnline.Builder.class);
    }

    public static final int TX2ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object tx2Id_;
    /**
     * <code>string tx2Id = 1;</code>
     */
    public java.lang.String getTx2Id() {
      java.lang.Object ref = tx2Id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tx2Id_ = s;
        return s;
      }
    }
    /**
     * <code>string tx2Id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTx2IdBytes() {
      java.lang.Object ref = tx2Id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tx2Id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TX2IP_FIELD_NUMBER = 2;
    private volatile java.lang.Object tx2Ip_;
    /**
     * <code>string tx2Ip = 2;</code>
     */
    public java.lang.String getTx2Ip() {
      java.lang.Object ref = tx2Ip_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tx2Ip_ = s;
        return s;
      }
    }
    /**
     * <code>string tx2Ip = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTx2IpBytes() {
      java.lang.Object ref = tx2Ip_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tx2Ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTx2IdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, tx2Id_);
      }
      if (!getTx2IpBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, tx2Ip_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTx2IdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, tx2Id_);
      }
      if (!getTx2IpBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, tx2Ip_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.cormye.common.proto.TranData.ClientOnline)) {
        return super.equals(obj);
      }
      com.cormye.common.proto.TranData.ClientOnline other = (com.cormye.common.proto.TranData.ClientOnline) obj;

      boolean result = true;
      result = result && getTx2Id()
          .equals(other.getTx2Id());
      result = result && getTx2Ip()
          .equals(other.getTx2Ip());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TX2ID_FIELD_NUMBER;
      hash = (53 * hash) + getTx2Id().hashCode();
      hash = (37 * hash) + TX2IP_FIELD_NUMBER;
      hash = (53 * hash) + getTx2Ip().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.cormye.common.proto.TranData.ClientOnline parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cormye.common.proto.TranData.ClientOnline parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cormye.common.proto.TranData.ClientOnline parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cormye.common.proto.TranData.ClientOnline parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cormye.common.proto.TranData.ClientOnline parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cormye.common.proto.TranData.ClientOnline parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cormye.common.proto.TranData.ClientOnline parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.cormye.common.proto.TranData.ClientOnline parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.cormye.common.proto.TranData.ClientOnline parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.cormye.common.proto.TranData.ClientOnline parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.cormye.common.proto.TranData.ClientOnline parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.cormye.common.proto.TranData.ClientOnline parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.cormye.common.proto.TranData.ClientOnline prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *对应HeadType的CLIENT_ONLINE
     * </pre>
     *
     * Protobuf type {@code ClientOnline}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ClientOnline)
        com.cormye.common.proto.TranData.ClientOnlineOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cormye.common.proto.TranData.internal_static_ClientOnline_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cormye.common.proto.TranData.internal_static_ClientOnline_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cormye.common.proto.TranData.ClientOnline.class, com.cormye.common.proto.TranData.ClientOnline.Builder.class);
      }

      // Construct using com.cormye.common.proto.TranData.ClientOnline.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        tx2Id_ = "";

        tx2Ip_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cormye.common.proto.TranData.internal_static_ClientOnline_descriptor;
      }

      @java.lang.Override
      public com.cormye.common.proto.TranData.ClientOnline getDefaultInstanceForType() {
        return com.cormye.common.proto.TranData.ClientOnline.getDefaultInstance();
      }

      @java.lang.Override
      public com.cormye.common.proto.TranData.ClientOnline build() {
        com.cormye.common.proto.TranData.ClientOnline result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.cormye.common.proto.TranData.ClientOnline buildPartial() {
        com.cormye.common.proto.TranData.ClientOnline result = new com.cormye.common.proto.TranData.ClientOnline(this);
        result.tx2Id_ = tx2Id_;
        result.tx2Ip_ = tx2Ip_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cormye.common.proto.TranData.ClientOnline) {
          return mergeFrom((com.cormye.common.proto.TranData.ClientOnline)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.cormye.common.proto.TranData.ClientOnline other) {
        if (other == com.cormye.common.proto.TranData.ClientOnline.getDefaultInstance()) return this;
        if (!other.getTx2Id().isEmpty()) {
          tx2Id_ = other.tx2Id_;
          onChanged();
        }
        if (!other.getTx2Ip().isEmpty()) {
          tx2Ip_ = other.tx2Ip_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.cormye.common.proto.TranData.ClientOnline parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.cormye.common.proto.TranData.ClientOnline) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object tx2Id_ = "";
      /**
       * <code>string tx2Id = 1;</code>
       */
      public java.lang.String getTx2Id() {
        java.lang.Object ref = tx2Id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          tx2Id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string tx2Id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTx2IdBytes() {
        java.lang.Object ref = tx2Id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tx2Id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string tx2Id = 1;</code>
       */
      public Builder setTx2Id(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tx2Id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string tx2Id = 1;</code>
       */
      public Builder clearTx2Id() {
        
        tx2Id_ = getDefaultInstance().getTx2Id();
        onChanged();
        return this;
      }
      /**
       * <code>string tx2Id = 1;</code>
       */
      public Builder setTx2IdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        tx2Id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object tx2Ip_ = "";
      /**
       * <code>string tx2Ip = 2;</code>
       */
      public java.lang.String getTx2Ip() {
        java.lang.Object ref = tx2Ip_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          tx2Ip_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string tx2Ip = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTx2IpBytes() {
        java.lang.Object ref = tx2Ip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tx2Ip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string tx2Ip = 2;</code>
       */
      public Builder setTx2Ip(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tx2Ip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string tx2Ip = 2;</code>
       */
      public Builder clearTx2Ip() {
        
        tx2Ip_ = getDefaultInstance().getTx2Ip();
        onChanged();
        return this;
      }
      /**
       * <code>string tx2Ip = 2;</code>
       */
      public Builder setTx2IpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        tx2Ip_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ClientOnline)
    }

    // @@protoc_insertion_point(class_scope:ClientOnline)
    private static final com.cormye.common.proto.TranData.ClientOnline DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.cormye.common.proto.TranData.ClientOnline();
    }

    public static com.cormye.common.proto.TranData.ClientOnline getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ClientOnline>
        PARSER = new com.google.protobuf.AbstractParser<ClientOnline>() {
      @java.lang.Override
      public ClientOnline parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ClientOnline(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ClientOnline> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ClientOnline> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.cormye.common.proto.TranData.ClientOnline getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TransProtocol_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TransProtocol_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientOnline_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ClientOnline_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\"_\n\rTransProtocol\022\033\n\010pack" +
      "Type\030\001 \001(\0162\t.PackType\022%\n\014clientOnline\030\002 " +
      "\001(\0132\r.ClientOnlineH\000B\n\n\010PackBody\",\n\014Clie" +
      "ntOnline\022\r\n\005tx2Id\030\001 \001(\t\022\r\n\005tx2Ip\030\002 \001(\t*\035" +
      "\n\010PackType\022\021\n\rCLIENT_ONLINE\020\000B#\n\027com.cor" +
      "mye.common.protoB\010TranDatab\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_TransProtocol_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TransProtocol_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TransProtocol_descriptor,
        new java.lang.String[] { "PackType", "ClientOnline", "PackBody", });
    internal_static_ClientOnline_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ClientOnline_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ClientOnline_descriptor,
        new java.lang.String[] { "Tx2Id", "Tx2Ip", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
