// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.cormye.common.proto;

/**
 * <pre>
 *定义传输对象  也是整个数据包的根对象
 * </pre>
 *
 * Protobuf type {@code TransProtocol}
 */
public  final class TransProtocol extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:TransProtocol)
    TransProtocolOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TransProtocol.newBuilder() to construct.
  private TransProtocol(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TransProtocol() {
    packType_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TransProtocol(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            packType_ = rawValue;
            break;
          }
          case 18: {
            com.cormye.common.proto.ClientOnline.Builder subBuilder = null;
            if (packBodyCase_ == 2) {
              subBuilder = ((com.cormye.common.proto.ClientOnline) packBody_).toBuilder();
            }
            packBody_ =
                input.readMessage(com.cormye.common.proto.ClientOnline.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.cormye.common.proto.ClientOnline) packBody_);
              packBody_ = subBuilder.buildPartial();
            }
            packBodyCase_ = 2;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.cormye.common.proto.TranData.internal_static_TransProtocol_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.cormye.common.proto.TranData.internal_static_TransProtocol_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.cormye.common.proto.TransProtocol.class, com.cormye.common.proto.TransProtocol.Builder.class);
  }

  private int packBodyCase_ = 0;
  private java.lang.Object packBody_;
  public enum PackBodyCase
      implements com.google.protobuf.Internal.EnumLite {
    CLIENTONLINE(2),
    PACKBODY_NOT_SET(0);
    private final int value;
    private PackBodyCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PackBodyCase valueOf(int value) {
      return forNumber(value);
    }

    public static PackBodyCase forNumber(int value) {
      switch (value) {
        case 2: return CLIENTONLINE;
        case 0: return PACKBODY_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public PackBodyCase
  getPackBodyCase() {
    return PackBodyCase.forNumber(
        packBodyCase_);
  }

  public static final int PACKTYPE_FIELD_NUMBER = 1;
  private int packType_;
  /**
   * <pre>
   *数据包类型
   * </pre>
   *
   * <code>.PackType packType = 1;</code>
   */
  public int getPackTypeValue() {
    return packType_;
  }
  /**
   * <pre>
   *数据包类型
   * </pre>
   *
   * <code>.PackType packType = 1;</code>
   */
  public com.cormye.common.proto.PackType getPackType() {
    @SuppressWarnings("deprecation")
    com.cormye.common.proto.PackType result = com.cormye.common.proto.PackType.valueOf(packType_);
    return result == null ? com.cormye.common.proto.PackType.UNRECOGNIZED : result;
  }

  public static final int CLIENTONLINE_FIELD_NUMBER = 2;
  /**
   * <code>.ClientOnline clientOnline = 2;</code>
   */
  public boolean hasClientOnline() {
    return packBodyCase_ == 2;
  }
  /**
   * <code>.ClientOnline clientOnline = 2;</code>
   */
  public com.cormye.common.proto.ClientOnline getClientOnline() {
    if (packBodyCase_ == 2) {
       return (com.cormye.common.proto.ClientOnline) packBody_;
    }
    return com.cormye.common.proto.ClientOnline.getDefaultInstance();
  }
  /**
   * <code>.ClientOnline clientOnline = 2;</code>
   */
  public com.cormye.common.proto.ClientOnlineOrBuilder getClientOnlineOrBuilder() {
    if (packBodyCase_ == 2) {
       return (com.cormye.common.proto.ClientOnline) packBody_;
    }
    return com.cormye.common.proto.ClientOnline.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (packType_ != com.cormye.common.proto.PackType.PINGER.getNumber()) {
      output.writeEnum(1, packType_);
    }
    if (packBodyCase_ == 2) {
      output.writeMessage(2, (com.cormye.common.proto.ClientOnline) packBody_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (packType_ != com.cormye.common.proto.PackType.PINGER.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, packType_);
    }
    if (packBodyCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (com.cormye.common.proto.ClientOnline) packBody_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.cormye.common.proto.TransProtocol)) {
      return super.equals(obj);
    }
    com.cormye.common.proto.TransProtocol other = (com.cormye.common.proto.TransProtocol) obj;

    boolean result = true;
    result = result && packType_ == other.packType_;
    result = result && getPackBodyCase().equals(
        other.getPackBodyCase());
    if (!result) return false;
    switch (packBodyCase_) {
      case 2:
        result = result && getClientOnline()
            .equals(other.getClientOnline());
        break;
      case 0:
      default:
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PACKTYPE_FIELD_NUMBER;
    hash = (53 * hash) + packType_;
    switch (packBodyCase_) {
      case 2:
        hash = (37 * hash) + CLIENTONLINE_FIELD_NUMBER;
        hash = (53 * hash) + getClientOnline().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.cormye.common.proto.TransProtocol parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cormye.common.proto.TransProtocol parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cormye.common.proto.TransProtocol parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cormye.common.proto.TransProtocol parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cormye.common.proto.TransProtocol parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cormye.common.proto.TransProtocol parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cormye.common.proto.TransProtocol parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cormye.common.proto.TransProtocol parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cormye.common.proto.TransProtocol parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.cormye.common.proto.TransProtocol parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cormye.common.proto.TransProtocol parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cormye.common.proto.TransProtocol parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.cormye.common.proto.TransProtocol prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *定义传输对象  也是整个数据包的根对象
   * </pre>
   *
   * Protobuf type {@code TransProtocol}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:TransProtocol)
      com.cormye.common.proto.TransProtocolOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cormye.common.proto.TranData.internal_static_TransProtocol_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cormye.common.proto.TranData.internal_static_TransProtocol_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cormye.common.proto.TransProtocol.class, com.cormye.common.proto.TransProtocol.Builder.class);
    }

    // Construct using com.cormye.common.proto.TransProtocol.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      packType_ = 0;

      packBodyCase_ = 0;
      packBody_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.cormye.common.proto.TranData.internal_static_TransProtocol_descriptor;
    }

    @java.lang.Override
    public com.cormye.common.proto.TransProtocol getDefaultInstanceForType() {
      return com.cormye.common.proto.TransProtocol.getDefaultInstance();
    }

    @java.lang.Override
    public com.cormye.common.proto.TransProtocol build() {
      com.cormye.common.proto.TransProtocol result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.cormye.common.proto.TransProtocol buildPartial() {
      com.cormye.common.proto.TransProtocol result = new com.cormye.common.proto.TransProtocol(this);
      result.packType_ = packType_;
      if (packBodyCase_ == 2) {
        if (clientOnlineBuilder_ == null) {
          result.packBody_ = packBody_;
        } else {
          result.packBody_ = clientOnlineBuilder_.build();
        }
      }
      result.packBodyCase_ = packBodyCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.cormye.common.proto.TransProtocol) {
        return mergeFrom((com.cormye.common.proto.TransProtocol)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.cormye.common.proto.TransProtocol other) {
      if (other == com.cormye.common.proto.TransProtocol.getDefaultInstance()) return this;
      if (other.packType_ != 0) {
        setPackTypeValue(other.getPackTypeValue());
      }
      switch (other.getPackBodyCase()) {
        case CLIENTONLINE: {
          mergeClientOnline(other.getClientOnline());
          break;
        }
        case PACKBODY_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.cormye.common.proto.TransProtocol parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.cormye.common.proto.TransProtocol) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int packBodyCase_ = 0;
    private java.lang.Object packBody_;
    public PackBodyCase
        getPackBodyCase() {
      return PackBodyCase.forNumber(
          packBodyCase_);
    }

    public Builder clearPackBody() {
      packBodyCase_ = 0;
      packBody_ = null;
      onChanged();
      return this;
    }


    private int packType_ = 0;
    /**
     * <pre>
     *数据包类型
     * </pre>
     *
     * <code>.PackType packType = 1;</code>
     */
    public int getPackTypeValue() {
      return packType_;
    }
    /**
     * <pre>
     *数据包类型
     * </pre>
     *
     * <code>.PackType packType = 1;</code>
     */
    public Builder setPackTypeValue(int value) {
      packType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *数据包类型
     * </pre>
     *
     * <code>.PackType packType = 1;</code>
     */
    public com.cormye.common.proto.PackType getPackType() {
      @SuppressWarnings("deprecation")
      com.cormye.common.proto.PackType result = com.cormye.common.proto.PackType.valueOf(packType_);
      return result == null ? com.cormye.common.proto.PackType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     *数据包类型
     * </pre>
     *
     * <code>.PackType packType = 1;</code>
     */
    public Builder setPackType(com.cormye.common.proto.PackType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      packType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *数据包类型
     * </pre>
     *
     * <code>.PackType packType = 1;</code>
     */
    public Builder clearPackType() {
      
      packType_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.cormye.common.proto.ClientOnline, com.cormye.common.proto.ClientOnline.Builder, com.cormye.common.proto.ClientOnlineOrBuilder> clientOnlineBuilder_;
    /**
     * <code>.ClientOnline clientOnline = 2;</code>
     */
    public boolean hasClientOnline() {
      return packBodyCase_ == 2;
    }
    /**
     * <code>.ClientOnline clientOnline = 2;</code>
     */
    public com.cormye.common.proto.ClientOnline getClientOnline() {
      if (clientOnlineBuilder_ == null) {
        if (packBodyCase_ == 2) {
          return (com.cormye.common.proto.ClientOnline) packBody_;
        }
        return com.cormye.common.proto.ClientOnline.getDefaultInstance();
      } else {
        if (packBodyCase_ == 2) {
          return clientOnlineBuilder_.getMessage();
        }
        return com.cormye.common.proto.ClientOnline.getDefaultInstance();
      }
    }
    /**
     * <code>.ClientOnline clientOnline = 2;</code>
     */
    public Builder setClientOnline(com.cormye.common.proto.ClientOnline value) {
      if (clientOnlineBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        packBody_ = value;
        onChanged();
      } else {
        clientOnlineBuilder_.setMessage(value);
      }
      packBodyCase_ = 2;
      return this;
    }
    /**
     * <code>.ClientOnline clientOnline = 2;</code>
     */
    public Builder setClientOnline(
        com.cormye.common.proto.ClientOnline.Builder builderForValue) {
      if (clientOnlineBuilder_ == null) {
        packBody_ = builderForValue.build();
        onChanged();
      } else {
        clientOnlineBuilder_.setMessage(builderForValue.build());
      }
      packBodyCase_ = 2;
      return this;
    }
    /**
     * <code>.ClientOnline clientOnline = 2;</code>
     */
    public Builder mergeClientOnline(com.cormye.common.proto.ClientOnline value) {
      if (clientOnlineBuilder_ == null) {
        if (packBodyCase_ == 2 &&
            packBody_ != com.cormye.common.proto.ClientOnline.getDefaultInstance()) {
          packBody_ = com.cormye.common.proto.ClientOnline.newBuilder((com.cormye.common.proto.ClientOnline) packBody_)
              .mergeFrom(value).buildPartial();
        } else {
          packBody_ = value;
        }
        onChanged();
      } else {
        if (packBodyCase_ == 2) {
          clientOnlineBuilder_.mergeFrom(value);
        }
        clientOnlineBuilder_.setMessage(value);
      }
      packBodyCase_ = 2;
      return this;
    }
    /**
     * <code>.ClientOnline clientOnline = 2;</code>
     */
    public Builder clearClientOnline() {
      if (clientOnlineBuilder_ == null) {
        if (packBodyCase_ == 2) {
          packBodyCase_ = 0;
          packBody_ = null;
          onChanged();
        }
      } else {
        if (packBodyCase_ == 2) {
          packBodyCase_ = 0;
          packBody_ = null;
        }
        clientOnlineBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.ClientOnline clientOnline = 2;</code>
     */
    public com.cormye.common.proto.ClientOnline.Builder getClientOnlineBuilder() {
      return getClientOnlineFieldBuilder().getBuilder();
    }
    /**
     * <code>.ClientOnline clientOnline = 2;</code>
     */
    public com.cormye.common.proto.ClientOnlineOrBuilder getClientOnlineOrBuilder() {
      if ((packBodyCase_ == 2) && (clientOnlineBuilder_ != null)) {
        return clientOnlineBuilder_.getMessageOrBuilder();
      } else {
        if (packBodyCase_ == 2) {
          return (com.cormye.common.proto.ClientOnline) packBody_;
        }
        return com.cormye.common.proto.ClientOnline.getDefaultInstance();
      }
    }
    /**
     * <code>.ClientOnline clientOnline = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.cormye.common.proto.ClientOnline, com.cormye.common.proto.ClientOnline.Builder, com.cormye.common.proto.ClientOnlineOrBuilder> 
        getClientOnlineFieldBuilder() {
      if (clientOnlineBuilder_ == null) {
        if (!(packBodyCase_ == 2)) {
          packBody_ = com.cormye.common.proto.ClientOnline.getDefaultInstance();
        }
        clientOnlineBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.cormye.common.proto.ClientOnline, com.cormye.common.proto.ClientOnline.Builder, com.cormye.common.proto.ClientOnlineOrBuilder>(
                (com.cormye.common.proto.ClientOnline) packBody_,
                getParentForChildren(),
                isClean());
        packBody_ = null;
      }
      packBodyCase_ = 2;
      onChanged();;
      return clientOnlineBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:TransProtocol)
  }

  // @@protoc_insertion_point(class_scope:TransProtocol)
  private static final com.cormye.common.proto.TransProtocol DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.cormye.common.proto.TransProtocol();
  }

  public static com.cormye.common.proto.TransProtocol getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TransProtocol>
      PARSER = new com.google.protobuf.AbstractParser<TransProtocol>() {
    @java.lang.Override
    public TransProtocol parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TransProtocol(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TransProtocol> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TransProtocol> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.cormye.common.proto.TransProtocol getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

