// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.cormye.common.proto;

public final class TranData {
  private TranData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TransProtocol_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TransProtocol_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientOnline_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ClientOnline_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\"_\n\rTransProtocol\022\033\n\010pack" +
      "Type\030\001 \001(\0162\t.PackType\022%\n\014clientOnline\030\002 " +
      "\001(\0132\r.ClientOnlineH\000B\n\n\010PackBody\",\n\014Clie" +
      "ntOnline\022\r\n\005tx2Id\030\001 \001(\t\022\r\n\005tx2Ip\030\002 \001(\t*)" +
      "\n\010PackType\022\n\n\006PINGER\020\000\022\021\n\rCLIENT_ONLINE\020" +
      "\001B%\n\027com.cormye.common.protoB\010TranDataP\001" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_TransProtocol_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TransProtocol_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TransProtocol_descriptor,
        new java.lang.String[] { "PackType", "ClientOnline", "PackBody", });
    internal_static_ClientOnline_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ClientOnline_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ClientOnline_descriptor,
        new java.lang.String[] { "Tx2Id", "Tx2Ip", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
